# [Leaf](https://github.com/vrongmeal/leaf) configuration file.

# Root directory to watch.
# Defaults to current working directory.
root: .

# Exclude directories while watching.
# If certain directories are not excluded, it might reach a
# limitation where watcher doesn't start.
exclude:
  - DEFAULTS # This includes the default ignored directories
  - .gitignore
  - .gitlab-ci.yml
  - bin
  - _data
  - _data1
  - _data2
  - _data3
  - _index
  - certs
  - testdata

# Filters to apply on the watch.
# Filters starting with '+' are includent and then with '-'
# are excluded. This is not like exclude, these are still
# being watched yet can be excluded from the execution.
# These can include any regex supported by filepath.Match
# method or even a directory.
filters:
  - '+ go.mod'
  - '+ go.sum'
  - '+ *.go'
  - '+ cmd/'
  - '+ common/'
  - '+ index/'
  - '+ tools/'
  - '- api/v1/*go'
  - '- mage_output_file.go'

# Commands to be executed. These are run in the provided order.
exec:
  - mage build

# Stop the command chain when an error occurs
exit_on_err: true

# Delay after which commands are executed.
delay: 500ms
